filsys: main.o igetput.o iallfre.o ballfre.o name.o access.o log.o close.o create.o delete.o dir.o dirlt.o open.o rdwt.o format.o install.o halt.o
    cc -o filsys main.o igetput.o iallfre.o ballfre.o name.o access.o log.o close.o create.o delete.o dir.o dirlt.o open.o rdwt.o format.o install.o halt.o

main.o: main.c filesys.h
    cc -c main.c

igetput.o: igetput.c filesys.h
    cc -c igetput.c

iallfre.o: iallfre.c filesys.h
    cc -c iallfre.c

ballfre.o: ballfre.c filesys.h
    cc -c ballfre.c

name.o: name.c filesys.h
    cc -c name.c

access.o: access.c filesys.h
    cc -c access.c

log.o: log.c filesys.h
    cc -c log.c

close.o: close.c filesys.h
    cc -c close.c

create.o: create.c filesys.h
    cc -c create.c

delete.o: delete.c filesys.h
    cc -c delete.c

dir.o: dir.c filesys.h
    cc -c dir.c

dirlt.o: dirlt.c filesys.h
    cc -c dirlt.c

open.o: open.c filesys.h
    cc -c open.c

rdwt.o: rdwt.c filesys.h
    cc -c rdwt.c

format.o: format.c filesys.h
    cc -c format.c

install.o: install.c filesys.h
    cc -c install.c

halt.o: halt.c
    cc -c halt.c